version: '2'
services:
  php:
    build: .
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./app:/app:delegated
    ports:
      - '8000:80'
  db:
    image: postgres:latest
    restart: always
    ports:
      - "6432:5432"
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'library'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: